config/routes.rb
Autotracker::Application.routes.draw do
  root 'vehicles#index'
  resources :repairs

  resources :vehicles do
    resources :repairs
  end

end

app/models/repair.rb
class Repair < ActiveRecord::Base
  belongs_to :vehicle
  validates_presence_of :part
  validates_presence_of :cost
  validates_presence_of :date_completed
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  has_many :repairs, dependent: :destroy
  validates_presence_of :brand
  validates_presence_of :model
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/repairs_controller.rb
class RepairsController < ApplicationController
  before_action :set_repair, only: [:show, :edit, :update, :destroy]

  # GET /repairs
  # GET /repairs.json
  def index
    @repairs = Repair.all
  end

  # GET /repairs/1
  # GET /repairs/1.json
  def show
  end

  # GET /repairs/new
  def new
    @repair = Repair.new
    @vehicle = Vehicle.find(params[:vehicle_id])
  end

  # GET /repairs/1/edit
  def edit
  end

  # POST /repairs
  # POST /repairs.json
  def create
    @vehicle = Vehicle.find(params[:vehicle_id])
    @repair = @vehicle.repairs.create(repair_params)

    respond_to do |format|
      if @repair.save
        format.html { redirect_to @vehicle, notice: 'Maintenance record was successfully created.' }
        format.json { render action: 'show', status: :created, location: @repair }
      else
        format.html { render action: 'new' }
        format.json { render json: @repair.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /repairs/1
  # PATCH/PUT /repairs/1.json
  def update
    respond_to do |format|
      if @repair.update(repair_params)
        format.html { redirect_to vehicle_path(@repair.vehicle_id), notice: 'Maintenance record was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @repair.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repairs/1
  # DELETE /repairs/1.json
  def destroy
    @repair.destroy
    respond_to do |format|
      format.html { redirect_to vehicle_path(@repair.vehicle_id), notice: 'Maintenance record was successfully deleted.'}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_repair
      @repair = Repair.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def repair_params
      params.require(:repair).permit(:part, :cost, :date_completed)
    end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.all
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render action: 'show', status: :created, location: @vehicle }
      else
        format.html { render action: 'new' }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(:brand, :model, :year)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/repairs_helper.rb
module RepairsHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <%= link_to "auto tracker", vehicles_path, id: "logo" %>
        </div>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<%= render 'layouts/header'%>
<body>

<%= yield %>

</body>
</html>

app/views/repairs/_form.html.erb
<%= form_for([@vehicle, Repair.new]) do |f| %>
    <p>
        <%= f.label :part, "Vehicle Part" %>
        <%= f.text_field :part %> <br/>
        <%= f.label :cost, "Total Cost" %>
        <%= f.text_field :cost %><br/>
        <%= f.label :date_completed, "Date of Work Completion" %>
        <%= f.date_field :date_completed %><br/>
    </p>
    <p><%= f.submit "Submit"%></p>
<% end %>

app/views/repairs/edit.html.erb
<h1>Editing repair</h1>

<%= render 'form' %>

<%= link_to 'Show', @repair,  class:"button" %> |
<%= link_to 'Back', repairs_path,  class:"button" %>

app/views/repairs/index.html.erb
<h1>Listing repairs</h1>

<table>
  <thead>
    <tr>
      <th>Part</th>
      <th>Cost</th>
      <th>Date completed</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @repairs.each do |repair| %>
      <tr>
        <td><%= repair.part %></td>
        <td><%= repair.cost %></td>
        <td><%= repair.date_completed %></td>
        <td><%= link_to 'Show', repair %></td>
        <td><%= link_to 'Edit', edit_repair_path(repair) %></td>
        <td><%= link_to 'Destroy', repair, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/repairs/new.html.erb
<h1>New repair</h1>

<%= render 'form' %>

<%= link_to 'Back', repairs_path %>

app/views/repairs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Part:</strong>
  <%= @repair.part %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @repair.cost %>
</p>

<p>
  <strong>Date completed:</strong>
  <%= @repair.date_completed %>
</p>

<%= link_to 'Edit', edit_repair_path(@repair) %> |
<%= link_to 'Back', repairs_path %>

app/views/vehicles/_form.html.erb
<%= form_for(@vehicle) do |f| %>
  <% if @vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
      <% @vehicle.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :brand %><br>
    <%= f.text_field :brand %>
  </div>
  <div class="field">
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :odometer_reading %><br>
    <%= f.number_field :odometer_reading %>
  </div>
  <div class="field">
    <%= f.label :energy_type %><br>
    <%= f.text_field :energy_type %>
  </div>
  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-large btn-primary"%>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<h1>Editing vehicle</h1>

<%= render 'form' %>

<%= link_to 'Back', vehicles_path,  class:"button"%>

app/views/vehicles/index.html.erb
<h1>My Vehicles</h1>

<table>
  <thead>
    <tr>
      <th>Brand</th>
      <th>Model</th>
      <th>Year</th>
      <th>   </th>
      <th>Options</th>
    </tr>
  </thead>

  <tbody>
    <% @vehicles.each do |vehicle| %>
      <tr>
        <td><%= vehicle.brand %></td>
        <td><%= vehicle.model %></td>
        <td><%= vehicle.year %></td>
        <td><%= link_to 'Show', vehicle %></td>
        <td><%= link_to 'Edit', edit_vehicle_path(vehicle) %></td>
        <td><%= link_to 'Delete', vehicle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vehicle', new_vehicle_path, class:"button" %>

app/views/vehicles/new.html.erb
<h1>New vehicle</h1>

<%= render 'form' %>

<%= link_to 'Back', vehicles_path,  class:"button" %>

app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Vehicle Maintenance Record</h1>
<h2><%= @vehicle.year %> <%= @vehicle.brand %> <%= @vehicle.model %></h2>



<table>
    <thead>
    <tr>
        <th>Part</th>
        <th>Cost</th>
        <th>Date Completed</th>
        <th>   </th>
        <th>Options</th>
    </tr>
    </thead>

<div id="repairs">
     <% @vehicle.repairs.each do |repair| %>
        <tr>
            <td><%= repair.part %></td>
            <td>$<%= repair.cost %></td>
            <td><%= repair.date_completed %></td>
            <td><%= link_to 'Edit', edit_vehicle_repair_path(:vehicle, repair) %></td>
            <td><%= link_to 'Delete', repair, method: :delete %></td>
      </tr>
    <% end %>
</div>
</table>


<%= link_to 'Add Record', new_vehicle_repair_path(@vehicle), class:"button" %>
<%= link_to 'Back', vehicles_path, class:"button" %>